# Generated by Django 4.1.2 on 2023-02-28 18:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookmodel',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
